In [6]:
import pickle
import numpy as np

In [4]:
with open('data/credit.pkl', 'rb') as f:
    X_credit_treinamento, X_credit_teste, y_credit_treinamento, y_credit_teste = pickle.load(f)

In [7]:
X_credit = np.concatenate((X_credit_treinamento, X_credit_teste), axis=0)
X_credit.shape

(2000, 3)

In [8]:
y_credit = np.concatenate((y_credit_treinamento, y_credit_teste), axis=0)
y_credit.shape

(2000,)

In [2]:
rede_neural = pickle.load(open('rede_neural_finalizado.sav', 'rb'))
random_forest = pickle.load(open('random_forest_finalizado.sav', 'rb'))
svm = pickle.load(open('svm_finalizado.sav', 'rb'))

In [17]:
novo_registro = X_credit[1999]
novo_registro

array([-1.03572293, -0.93978122,  0.04244312])

In [18]:
novo_registro = novo_registro.reshape(1, -1)
novo_registro.shape

(1, 3)

In [19]:
rede_neural.predict(novo_registro)

array([1], dtype=int64)

In [20]:
random_forest.predict(novo_registro)

array([1], dtype=int64)

In [21]:
svm.predict(novo_registro)

array([1], dtype=int64)